apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: sbmvnpodinfo
  ports:
    - protocol: TCP
      nodePort: 30301
      port: 8090
      targetPort: 8090